//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenWilfart
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersTable
    {
        public System.Guid UserId { get; set; }
        public string UserName { get; set; }
        public string UserPasswd { get; set; }
        public Nullable<System.Guid> UserRoleId { get; set; }
        public string UserAdress { get; set; }
        public string UserCity { get; set; }
        public string UserPostCode { get; set; }
        public Nullable<System.DateTime> UserBirthDay { get; set; }
    }
}
